.github/workflows/build-and-types.yml, .github/workflows/e2e-tests.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml
These are 4 workflows that we use in the new OneFit frontend projects. The projects are mostly React and Next.js
The workflows include:
- [.github/workflows/build-and-types.yml](https://github.com/urbansportsclub/usc-reusable-workflows/pull/8/files#diff-cbf32240c18489c7b6f1fc9c92757486dbc78c3aaf84a0ec7a4bdd9bac9be24d) for checking types and making sure the build passes. It invokes `yarn build` in the project root which usually uses CRA or Next in the projects to check the types and build the project.
- [.github/workflows/lint.yml](https://github.com/urbansportsclub/usc-reusable-workflows/pull/8/files#diff-107e910e9f2ebfb9a741fa10b2aa7100cc1fc4f5f3aca2dfe78b905cbd73c0d2) for lining the project. We have a pretty standard, but extensive linter setup with ESLint and StyleLint. This makes sure …
=> Onefit frontend workflows

.github/workflows/e2e-tests.yml
The new Cypress update changed the API and broke this action. Maybe this will fix it? Can we merge to test? If not I'll investigate further.
=> Upgrade Cypress in e2e-tests.yml

.github/workflows/build-and-push-docker-image.yaml
Default behaviour didn't change. By default it still builds image only for `linux/amd64` platform. QEMU setup step adds 5-10 seconds to build time.
=> Support multi-platform builds

.github/workflows/deploy-to-k8s-cluster.yaml
When we deploy with this action, we don't know the flag to GitHub in which environment the deployment happened.
This PR will generate a deployment event for the four key metrics we want to track.
=> Add environment

.github/workflows/test-go.yaml
Added a new reusable workflow to be used for the go services.
We already have an existing one, but that one is for Javascript and it is used only for [urbansports/usg-web-careers](https://github.com/urbansportsclub/usg-web-careers/blob/2be323d7c4f5dde96c34412d2db5e3ab8639ecc3/.github/workflows/ci.yml#L20) and [urbansports/onefit-web-b2b](https://github.com/urbansportsclub/onefit-web-b2b/blob/8ce06070c637c3c6b06e41f60e0732722d0a384b/.github/workflows/ci.yml#L19)
Search result:
https://github.com/search?q=org%3Aurbansportsclub++%22urbansportsclub%2Fusc-reusable-workflows%2F.github%2Fworkflows%2Funit-tests%22&type=code
Usage:
```yaml
reusable-test:
name: Test
uses: urbansportsclub/usc-reusable-workflows/.github/workflows/test-go.yaml@main
secrets: inherit
```
=> add new reusable workflow for testing golang apps

.github/workflows/test-go.yaml
Expose the `runner` to allow running the tests on different runners if necessary.
- The execution of this workflow on `nonroot` fails due to the missing `gcc` executable: https://github.com/urbansportsclub/invoice-srv/actions/runs/3740175590/jobs/6348330226#step:6:96
Also, including the `Configure private repo` which was missing from the initial implementation.
=> Update test-go workflow to expose the runner and add GH config

.github/workflows/linter.yaml
This is one of the few env vars for super linter that doesn't support a configuration file. All the other languages/technologies that we use at USG can be configured via a config file in `.github/linters`
=> add ignore missing schemas for kubeconform validation

.github/workflows/linter.yaml
KUBEVAL was removed [here](https://github.com/github/super-linter/pull/3800/files) but they haven't yet created a new release that has it, today the latest version is [v4.10.1](https://github.com/github/super-linter/releases/tag/v4.10.1).
The new option is just to support the BC that will happen.
=> add also kubeval for current v4 version

.github/workflows/linter.yaml
Due to an issue with super-linter that doesn't execute the `golangci-lint` properly, sometimes it might isolate changes and this will trigger a specific lint called `typecheck`, which validates to see if a function/struct/const/etc... really exists or not. Because super-lint only is triggered to the modified files, you might have a problem to be linting a file that doesn't create that property, but instead, only use it.
To bypass that, we can use the golangci-lint action instead, which will validate the whole source code and ensuring that we will not lose context in the lint process.
**resources**
https://github.com/github/super-linter/issues/3596
https://github.com/golangci/golangci-lint/issues/1909
https://github.com/github/super-linter/issues/143
=> disable super linter golang lint and use golangci-lint instead

.github/workflows/linter.yaml
Kubeform is giving a lot of complains with `Missing 'kind' key` on our helm chart templates. I didn't found a proper way to fix it, and I decided to disable by default.
=> Disable KUBEFORM linter by default

.github/workflows/linter.yaml
We found that having some linters enabled by default to true and others on false it will fail ([like in this PR](https://github.com/urbansportsclub/invoice-srv/actions/runs/4240919389/jobs/7370494071#step:5:76)) based on the documentation from super-linter.
> ## Environment variables
> 
> The super-linter allows you to pass the following `ENV` variables to be able to trigger different functionality.
> 
> _Note:_ All the `VALIDATE_[LANGUAGE]` variables behave in a very specific way:
> 
> - If none of them are passed, then they all default to true.
> - If any one of the variables are set to true, we default to leaving any unset variable to false (only validate those languages).
> - If any one of the variables are set to false, we default to leaving any unset variable to true (only exclude …
=> Default false for specific linter validation

.github/workflows/sonarqube-scan.yaml
This will help us to identify and work properly on SonarQube, allowing us to separate new changes from version to version, instead getting quality gate automatically fired because it gets every change from previous and actual as new changes since there is no new version tagged.
=> Set sonar.projectVersion

.github/workflows/sonarqube-scan.yaml, README.md
We moved the sonar token secret to the organization level and renamed the variable for better naming
=> Rename sonarqube token variable name

.github/workflows/test-go.yaml
There is an issue with container implementations that are affected with changes in the standard library. More here https://github.com/testcontainers/testcontainers-go/issues/1359, for the meantime, while https://github.com/moby/moby/pull/45942 is not merged and https://github.com/testcontainers/testcontainers-go/issues/1359#issuecomment-1632456255 is not followed, we cannot block our engineers. For this reason, I am adding the flag `-short` to avoid running all the container specific tests.
=> run go tests in short mode

.github/workflows/test-go.yaml
To re-enable the execution of integration test, we can downgrade go version one patch before, since the issue related with the containers was caused in the version 1.20.6 as mentioned here https://github.com/testcontainers/testcontainers-go/issues/1359#issuecomment-1632858266 and here https://github.com/testcontainers/testcontainers-go/issues/1359#issuecomment-1632866663
=> downgrade golang version and remove -short

.github/workflows/test-go.yaml
Since the issues from last time were fixed and new projects can easily update their dependencies from testcontainers' issue, we can return to the stable version and have the new features from Go 1.21 available for usage.
=> stable version for golang

.github/workflows/linter.yaml
`golangci-lint` introduced [an issue](https://github.com/golangci/golangci-lint/issues/4353) in v1.56 which causes our linter workflow to fail with the following:
```bash
level=error msg="Running error: can't run linter goanalysis_metalinter\nthe_only_name: cannot find rule: enforce-repeated-arg-type-style"
```
This will likely be fixed in a v1.56.1 release of the tool soon. And, there is a [documented work-around](https://github.com/golangci/golangci-lint/issues/4353#issuecomment-1932470454) that each project can adopt in their `.golangci.yaml` file. However, to unblock everyone at once, the best option, I think, is to pin us to the previous release.
We should be aware that we don't get too far behind on versions though!
Note, per the [action …
=> task: Pin golang-ci-lint to non-broken version

.github/workflows/test-go.yaml
It will fix the [following error](https://github.com/actions/setup-go/issues/427) in many CI runs.
=> Error with setup.go and cache

.github/workflows/internal-automerge.yaml
The internal automerge is supposed to work in this repo and not as a reusable workflow. As of today, github actions does not support having folders inside the workflows folder so I added a comment to specify that this workflow is for internal use.
=> internal automerge

.github/workflows/linter.yaml
In the linter reusable workflow there is an option **only-new-issues** which is set to **true** which means that only new issues will be reported if it’s a pull request.
But this option generates golangci-lint command using **—new-from-patch** option which will make linter to skip the issues if they are not reported as the same line as the changes (it uses git diff, the issue is described here: https://golangci-lint.run/usage/faq/#why---new-from-rev-or---new-from-patch-dont-seem-to-be-working-in-some-cases).
As a fix, we have added new input for linter reusable workflow **enable_whole_files** which, if set to **true**, includes **—whole-files** option which makes linter to show the issues in any part of files that are updated. This may lead for some old issues that weren’t reported before …
=> fix linter issue

.github/workflows/build-and-push-docker-image.yaml
- docker/build-push-action@v5 was not implementing the usage of secrets
=> add secrets support to image build

.github/workflows/build-and-push-docker-image.yaml
We allow to set the push to false in case someone wants to build their image without pushing to the registry (for example, for testing or to check for build errors).
The default value is true so this will not affect any existing project using this action.
=> Build without pushing

.github/workflows/sonarqube-scan.yaml, .github/workflows/unit-test-js.yml
- When using `download-artifact` with only the `name` value, it will download all files / directories within the artifact to the root of the project folder
- Should make use of the `path:`  value when we want to, to allow for the files to be downloaded to a custom dir
- This is useful with Sonarqube as we can then point our `sonar.javascript.lcov.reportPaths` to a specific directory
- e.g.
- `sonar.javascript.lcov.reportPaths=./coverage/lcov.info`
=> Add Custom Download Path Value to Sonarqube Download Artifact
